#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running prettier on staged files..."
npx prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again